============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-8.3.2, pluggy-1.5.0 -- /home/yasnoz/.pyenv/versions/3.10.6/envs/taxifare-env/bin/python
cachedir: .pytest_cache
rootdir: /home/yasnoz/code/yasnoz/07-ML-Ops/04-Predict-in-production/data-fast-api/tests
configfile: pytest_kitt.ini
plugins: anyio-3.7.1, asyncio-0.24.0
asyncio: mode=strict, default_loop_scope=None
collecting ... collected 18 items

tests/api/test_cloud_endpoints.py::test_root_is_up PASSED                [  5%]
tests/api/test_cloud_endpoints.py::test_root_returns_greeting PASSED     [ 11%]
tests/api/test_cloud_endpoints.py::test_predict_is_up PASSED             [ 16%]
tests/api/test_cloud_endpoints.py::test_predict_is_dict PASSED           [ 22%]
tests/api/test_cloud_endpoints.py::test_predict_has_key PASSED           [ 27%]
tests/api/test_cloud_endpoints.py::test_cloud_api_predict PASSED         [ 33%]
tests/api/test_docker_endpoints.py::test_root_is_up FAILED               [ 38%]
tests/api/test_docker_endpoints.py::test_root_returns_greeting FAILED    [ 44%]
tests/api/test_docker_endpoints.py::test_predict_is_up FAILED            [ 50%]
tests/api/test_docker_endpoints.py::test_predict_is_dict FAILED          [ 55%]
tests/api/test_docker_endpoints.py::test_predict_has_key FAILED          [ 61%]
tests/api/test_docker_endpoints.py::test_cloud_api_predict FAILED        [ 66%]
tests/api/test_endpoints.py::test_root_is_up PASSED                      [ 72%]
tests/api/test_endpoints.py::test_root_returns_greeting PASSED           [ 77%]
tests/api/test_endpoints.py::test_predict_is_up PASSED                   [ 83%]
tests/api/test_endpoints.py::test_predict_is_dict PASSED                 [ 88%]
tests/api/test_endpoints.py::test_predict_has_key PASSED                 [ 94%]
tests/api/test_endpoints.py::test_predict_val_is_float PASSED            [100%]

=================================== FAILURES ===================================
_______________________________ test_root_is_up ________________________________

    @pytest.mark.asyncio
    async def test_root_is_up():
>       assert docker_port # Stop if no docker port found
E       assert None

tests/api/test_docker_endpoints.py:48: AssertionError
__________________________ test_root_returns_greeting __________________________

    @pytest.mark.asyncio
    async def test_root_returns_greeting():
>       assert docker_port # Stop if no docker port found
E       assert None

tests/api/test_docker_endpoints.py:56: AssertionError
______________________________ test_predict_is_up ______________________________

    @pytest.mark.asyncio
    async def test_predict_is_up():
>       assert docker_port # Stop if no docker port found
E       assert None

tests/api/test_docker_endpoints.py:64: AssertionError
_____________________________ test_predict_is_dict _____________________________

    @pytest.mark.asyncio
    async def test_predict_is_dict():
>       assert docker_port # Stop if no docker port found
E       assert None

tests/api/test_docker_endpoints.py:72: AssertionError
_____________________________ test_predict_has_key _____________________________

    @pytest.mark.asyncio
    async def test_predict_has_key():
>       assert docker_port # Stop if no docker port found
E       assert None

tests/api/test_docker_endpoints.py:81: AssertionError
____________________________ test_cloud_api_predict ____________________________

    @pytest.mark.asyncio
    async def test_cloud_api_predict():
>       assert docker_port # Stop if no docker port found
E       assert None

tests/api/test_docker_endpoints.py:88: AssertionError
=========================== short test summary info ============================
FAILED tests/api/test_docker_endpoints.py::test_root_is_up - assert None
FAILED tests/api/test_docker_endpoints.py::test_root_returns_greeting - asser...
FAILED tests/api/test_docker_endpoints.py::test_predict_is_up - assert None
FAILED tests/api/test_docker_endpoints.py::test_predict_is_dict - assert None
FAILED tests/api/test_docker_endpoints.py::test_predict_has_key - assert None
FAILED tests/api/test_docker_endpoints.py::test_cloud_api_predict - assert None
================== 6 failed, 12 passed, 9 warnings in 28.49s ===================
